sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

services: mongodb

node_js:
  - "8"

matrix:
  fast_finish: true

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install

script:
  - npm run test:api
  - npm run ci:travis